#!/bin/bash

# Simple driver script for Psi4, modify for your environment
# Currently it simply runs Psi4 with two threads

# Specify the Scratch path (default is /tmp)
# export PSI_SCRATCH=

psi4 -n 2 $@

