package:
  name: geometric
  version: "0.9.7.2"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy {{ numpy }}
    - networkx
    - six

test:
  requires:
    - pytest
  imports:
    - geometric

about:
  home: https://github.com/leeping/geomeTRIC
  license: 
